###TYPES###

##Groups##
type GroupBucket {
  sourceName: String
  sourceId: String
  groups: [String]
}

type GroupSource {
  sourceName: String
  sourceId: String
}

type GroupMembership {
  name: String
  iamid: String
  loginId: String
  employeeId: String
  email: String
  groups: [GroupBucket]
}

type GroupMember {
  name: String
  iamid: String
  email: String
}

type GroupById {
  groupName: String
  groupSource: String
  groupId: String
  groupMembers: [GroupMember]
}

##Roles##
type Role {
  roleName: String
  roleId: String
  description: String
  enabled: Boolean
  requestable: Boolean
}

type RoleMembership {
  name: String
  iamid: String
  loginId: String
  employeeId: String
  email: String
  roles: [Role]
}

type RoleById {
  roleName: String
  roleId: String
  description: String
  enabled: Boolean
  requestable: Boolean
  roleMembers: [GroupMember]
}

##People##
type ProvisioningStatus {
  primary: String
  primary_override: String
  cosmos_affiliate: String
  cpe_affiliate: String
  employee: String
  faculty: String
  health_affiliate: String
  student: String
  student_applicant: String
  temporary_affiliate: String
  ucanr_affiliate: String
  usda_whnrc_affiliate: String
}

type EmploymentStatus {
  is_without_salary: String
  is_academic: String
  is_academic_senate: String
  is_academic_federation: String
  is_faculty: String
  is_ladder_rank: String
  is_manager: String
  is_teaching_faculty: String
  is_msp: String
  is_ssp: String
  is_supervisor: String
  is_msp_career: String
  is_msp_career_partial_year: String
  is_msp_contract: String
  is_msp_casual: String
  is_msp_senior_management: String
  is_ssp_career: String
  is_ssp_career_partial_year: String
  is_ssp_contract: String
  is_ssp_casual: String
  is_ssp_casual_restricted: String
  is_ssp_per_diem: String
  is_ssp_floater: String
  is_health_employee: String
  is_campus_employee: String
}

type Affiliation {
  employee: String
  faculty: String
  student: String
  student_applicant: String
  health_affiliate: String
  temporary_affiliate: String
  cosmos_affiliate: String
  cpe_affiliate: String
  ucanr_affiliate: String
  usda_whnrc_affiliate: String
}

type NameRecord {
  lived_first_name: String
  lived_middle_name: String
  lived_last_name: String
  lived_pronouns: String
  legal_first_name: String
  legal_middle_name: String
  legal_last_name: String
}

type MailId {
  campus: String
  health: String
}

type IdentityIds {
  iam_id: String
  login_id: String
  student_id: String
  mothra_id: String
  employee_id: String
  mail_id: MailId
  pidm: String
  pps_id: String
  cosmos_id: String
  cpe_id: String
  health_affiliate_id: String
  ucanr_id: String
  usda_whnrc_id: String
  affiliate_id: String
  ucnet_id: String
}

type EmailAddresses {
  campus: String
  health: String
  personal: String
}

type PhoneNumbers {
  primary: String
  work: String
  personal: String
}

type StudentAssociation {
  college_code: String
  college_title: String
  major_code: String
  major_title: String
  academic_level: String
  class_level: String
}

type EmployeeAssociation {
  iam_id: String
  employee_record: String
  employee_id: String
  position_number: String
  position_title: String
  "Values: N (Not Applicable), S (Secondary Job), P (Primary Job)."
  job_indicator: String
  relationship_to_organization: String
  employee_classification: String
  employee_classification_description: String
  status: String
  hire_date: String
  start_date: String
  termination_date: String
  fte_percentage: String
  job_type_id: String
  job_type_description: String
  job_family_id: String
  job_family_description: String
  organization_id: String
  organization_title: String
  division_id: String
  division_title: String
  subdivision_id: String
  subdivision_title: String
  subdivision_l4_id: String
  subdivision_l4_title: String
  business_unit_id: String
  business_unit_title: String
  department_id: String
  department_title: String
  department_short_title: String
  reports_to_position: String
  reports_to_iam_id: String
  reports_to_employee_id: String
  is_health_position: String
  is_campus_position: String
}

type Person {
  iam_id: ID
  displayname: String
  birth_date: String
  manager_iam_id: String
  provisioning_status: [ProvisioningStatus]
  affiliation: Affiliation
  employment_status: EmploymentStatus
  name: [NameRecord]
  id: [IdentityIds]
  email: [EmailAddresses]
  phone: [PhoneNumbers]
  student_association: [StudentAssociation]
  employee_association: [EmployeeAssociation]
  modified_date: String
  create_date: String
}

##Position Association##

type PpsAssociationRecord {
  iam_id: String
  reports_to_iam_id: String
  reports_to_employee_id: String
  employee_id: String
  employee_record: String
  position_number: String
  position_title: String
  "Values: N (Not Applicable), S (Secondary Job), P (Primary Job)."
  job_indicator: String
  relationship_to_organization: String
  employee_classification: String
  employee_classification_description: String
  status: String
  hire_date: String
  start_date: String
  termination_date: String
  fte_percentage: String
  reports_to_position: String
  job_type_id: String
  job_type_description: String
  job_family_id: String
  job_family_description: String
  organization_id: String
  organization_title: String
  division_id: String
  division_title: String
  subdivision_id: String
  subdivision_title: String
  business_unit_id: String
  business_unit_title: String
  department_id: String
  department_title: String
  department_short_title: String
  is_health_position: String
  is_campus_position: String
  modified_date: String
  create_date: String
}

##Student Association##
type SisAssociationRecord {
  iam_id: String
  pidm: String
  student_id: String
  college_code: String
  college_title: String
  major_code: String
  major_title: String
  lvl_affiliation_code: String
  cls_affiliation_code: String
  rank: String
  modified_date: String
  create_date: String
}

##College Info##
type College {
  college_code: String
  college_title: String
}

##Major Info##
type Major {
  major_code: String
  major_title: String
  major_status: String
}

type JobTypeId {
  job_type_id: String
  job_type_description: String
}

##Organizations##
type OrganizationDepartmentNode {
  department_id: String
  department_title: String
  department_short_title: String
}

type OrganizationSubdivisionL4Node {
  subdivision_l4_id: String
  subdivision_l4_title: String
  departments: [OrganizationDepartmentNode]
}

type OrganizationSubdivisionNode {
  subdivision_id: String
  subdivision_title: String
  subdivision_l4s: [OrganizationSubdivisionL4Node]
}

type OrganizationDivisionNode {
  division_id: String
  division_title: String
  subdivisions: [OrganizationSubdivisionNode]
}

type OrganizationNode {
  organization_id: String
  organization_title: String
  divisions: [OrganizationDivisionNode]
}

type OrganizationDivisionDetail {
  organization_id: String
  organization_title: String
  division_id: String
  division_title: String
  subdivisions: [OrganizationSubdivisionNode]
}

type OrganizationSubdivisionDetail {
  organization_id: String
  organization_title: String
  division_id: String
  division_title: String
  subdivision_id: String
  subdivision_title: String
  subdivision_l4s: [OrganizationSubdivisionL4Node]
}

type OrganizationSubdivisionL4Detail {
  organization_id: String
  organization_title: String
  division_id: String
  division_title: String
  subdivision_id: String
  subdivision_title: String
  subdivision_l4_id: String
  subdivision_l4_title: String
  departments: [OrganizationDepartmentNode]
}

type OrganizationDepartmentDetail {
  department_id: String
  department_title: String
  department_short_title: String
  subdivision_id: String
  subdivision_title: String
  subdivision_l4_id: String
  subdivision_l4_title: String
  division_id: String
  division_title: String
  organization_id: String
  organization_title: String
}

##Accounts##
type AccountSourceCount {
  sourceId: String
  sourceName: String
  accountCount: Int
}

type AccountSource {
  sourceId: String
  sourceName: String
}

type AccountSummary {
  sourceName: String
  accountId: String
  isAdmin: String
  objectPath: String
  objectType: String
  lastLoginTime: String
  created: String
  modified: String
}

type AccountLookupIdentity {
  identityId: String
  name: String
  iamid: String
  loginId: String
  email: String
  accounts: [AccountSummary]
}

##Meta Info##
type Meta {
  x_total_count: Int
  x_response_count: Int
}

type QueryParameterValidationError {
  parameter: String
  value: String
  message: String
}

enum AcademicLevel {
  GR
  LW
  MD
  ND
  U2
  UG
  UL
  VM
  graduate
  undergrad
}

enum ClassLevel {
  D1
  D2
  FR
  GM
  JR
  L1
  L2
  L3
  LM
  M1
  M2
  M3
  M4
  ND
  PB
  SO
  SR
  U2
  UL
  V1
  V2
  V3
  V4
  VALUE_00
}

###INPUTS###
###Query parameter / filters for queries###
input PeopleFilterInput {
  iamid: String
  firstname: String
  lastname: String
  firstnamelike: String
  lastnamelike: String
  manager_iam_id: String
  iamids: [String]
  email: String
  emails: [String]
  loginid: String
  employeeid: String
  studentid: String
  mailid: String
  pidm: String
  mothraid: String
  pps_id: String
  cosmos_id: String
  cpe_id: String
  health_affiliate_id: String
  ucanr_id: String
  usda_whnrc_id: String
  affiliate_id: String
  ucnet_id: String
  affiliationContains: String
  affiliationNotContains: String
  affiliationState: String = "withAffiliation"
  department: String
  collegecode: String
  majorcode: String
  academic_level: AcademicLevel
  class_level: ClassLevel
  organizationid: String
  divisionid: String
  subdivisionid: String
  subdivisionl4id: String
  employmentStatus: String
  count: Boolean = false
  modifiedsince: String
  limit: Int = 10000
  offset: Int = 0
}

input CollegesFilterInput {
  college_code: String
  college_title: String
}

input MajorsFilterInput {
  major_code: String
  major_title: String
  major_status: String
}

input GroupsFilterInput {
  source: String
  limit: Int = 10000
}

input GroupMembershipFilterInput {
  iamid: String
  iamids: [String]
  email: String
  loginid: String
  employeeid: String
  source: String
  limit: Int = 10000
}

input GroupsByIdFilterInput {
id: String!
limit: Int = 10000
}

input RolesFilterInput {
  limit: Int = 10000
}

input RoleMembershipFilterInput {
  iamid: String
  iamids: [String]
  email: String
  loginid: String
  employeeid: String
  limit: Int = 10000
}

input RolesByIdFilterInput {
  id: String!
  limit: Int = 10000
}

input EmployeeAssociationFilterInput {
iamid: String
iamids: [String]
loginid: String
employeeid: String
jobtypeid: String
organizationid: String
departmentid: String
divisionid: String
subdivisionid: String
subdivisionl4id: String
count: Boolean = false
modifiedsince: String
offset: Int = 0
limit: Int = 1000
}

  input EmployeeAssociationJobTypeIdsFilterInput {
job_type_id: String
jobtypeid: String
  }

  input StudentAssociationFilterInput {
iamid: String
iamids: [String]
pidm: String
studentid: String
majorcode: String
collegecode: String
count: Boolean = false
modifiedsince: String
offset: Int = 0
limit: Int = 1000
}

input OrganizationHierarchyFilterInput {
  departmentid: String
  subdivisionid: String
  subdivisionl4id: String
  organizationid: String
  divisionid: String
  limit: Int = 10000
}

input OrganizationByIdFilterInput {
  id: String!
  departmentid: String
  subdivisionid: String
  subdivisionl4id: String
  organizationid: String
  divisionid: String
  limit: Int = 10000
}

input AccountLookupFilterInput {
  iamid: String
  iamids: [String]
  email: String
  loginid: String
}

##Results##
type PeopleResult {
  results: [Person]
  meta: Meta
  errors: [QueryParameterValidationError]
}

type EmployeeAssociationResult {
  results: [PpsAssociationRecord]
  meta: Meta
  errors: [QueryParameterValidationError]
}

type StudentAssociationResult {
  results: [SisAssociationRecord]
  meta: Meta
  errors: [QueryParameterValidationError]
}

type MajorsResult {
  results: [Major]
  errors: [QueryParameterValidationError]
}

type JobTypeIdsResult {
  results: [JobTypeId]
  errors: [QueryParameterValidationError]
}

type CollegeResult {
  results: [College]
  errors: [QueryParameterValidationError]
}

type GroupsResult {
  results: [GroupBucket]
  errors: [QueryParameterValidationError]
}

type GroupSourceResults {
  results: [GroupSource]
  errors: [QueryParameterValidationError]
}

type GroupMembershipResult {
  results: [GroupMembership]
  errors: [QueryParameterValidationError]
}

type GroupByIdResult {
  results: GroupById
  errors: [QueryParameterValidationError]
}

type RolesResult {
  results: [Role]
  errors: [QueryParameterValidationError]
}

type RoleMembershipResult {
  results: [RoleMembership]
  errors: [QueryParameterValidationError]
}

type RoleByIdResult {
  results: RoleById
  errors: [QueryParameterValidationError]
}

type OrganizationsResult {
  results: [OrganizationNode]
  errors: [QueryParameterValidationError]
}

type OrganizationByIdResult {
  results: OrganizationNode
  errors: [QueryParameterValidationError]
}

type OrganizationDivisionByIdResult {
  results: OrganizationDivisionDetail
  errors: [QueryParameterValidationError]
}

type OrganizationSubdivisionByIdResult {
  results: OrganizationSubdivisionDetail
  errors: [QueryParameterValidationError]
}

type OrganizationSubdivisionL4ByIdResult {
  results: OrganizationSubdivisionL4Detail
  errors: [QueryParameterValidationError]
}

type OrganizationDepartmentByIdResult {
  results: OrganizationDepartmentDetail
  errors: [QueryParameterValidationError]
}

type AccountSourceCountsResult {
  results: [AccountSourceCount]
  errors: [QueryParameterValidationError]
}

type AccountSourcesResult {
  results: [AccountSource]
  errors: [QueryParameterValidationError]
}

type AccountLookupResult {
  results: [AccountLookupIdentity]
  errors: [QueryParameterValidationError]
}

##Query types##
type Query {
  #Colleges
  colleges(filter: CollegesFilterInput): CollegeResult

  #Majors
  majors(filter: MajorsFilterInput): MajorsResult

  #People
  people(filter: PeopleFilterInput): PeopleResult
  people_students(filter: PeopleFilterInput): PeopleResult
  people_employees(filter: PeopleFilterInput): PeopleResult
  people_faculty(filter: PeopleFilterInput): PeopleResult
  people_external(filter: PeopleFilterInput): PeopleResult

  #Groups
  groups(filter: GroupsFilterInput): GroupsResult
  groupSources: GroupSourceResults
  groupMembership(filter: GroupMembershipFilterInput): GroupMembershipResult
  groupById(filter: GroupsByIdFilterInput): GroupByIdResult

  #Roles
  roles(filter: RolesFilterInput): RolesResult
  roleMembership(filter: RoleMembershipFilterInput): RoleMembershipResult
  roleById(filter: RolesByIdFilterInput): RoleByIdResult

  #Position Association
  employee_association(filter: EmployeeAssociationFilterInput): EmployeeAssociationResult
  employee_association_jobtypeids(filter: EmployeeAssociationJobTypeIdsFilterInput): JobTypeIdsResult

  #Organizations
  organizations(filter: OrganizationHierarchyFilterInput): OrganizationsResult
  organizationById(filter: OrganizationByIdFilterInput): OrganizationByIdResult
  organizationDivisions(filter: OrganizationHierarchyFilterInput): OrganizationsResult
  organizationDivisionById(filter: OrganizationByIdFilterInput): OrganizationDivisionByIdResult
  organizationSubdivisions(filter: OrganizationHierarchyFilterInput): OrganizationsResult
  organizationSubdivisionById(filter: OrganizationByIdFilterInput): OrganizationSubdivisionByIdResult
  organizationSubdivisionL4s(filter: OrganizationHierarchyFilterInput): OrganizationsResult
  organizationSubdivisionL4ById(filter: OrganizationByIdFilterInput): OrganizationSubdivisionL4ByIdResult
  organizationDepartments(filter: OrganizationHierarchyFilterInput): OrganizationsResult
  organizationDepartmentById(filter: OrganizationByIdFilterInput): OrganizationDepartmentByIdResult

  #Accounts
  accounts: AccountSourceCountsResult
  accountLookup(filter: AccountLookupFilterInput): AccountLookupResult
  accountSources: AccountSourcesResult

  #Student Association
  student_association(filter: StudentAssociationFilterInput): StudentAssociationResult
}

schema {
  query: Query
}
